sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - source
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  committer_from_gh: true
  target_branch: master
  on:
    branch: source
  local-dir: public

